DenimSACCOS/Models/Gallery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DenimSACCOS.Models
{
    public class Gallery
    {

        public string ImageName { get; set; }
        public string ImagePath { get; set; }
        public bool Status { get; set; }
        public IEnumerable<string> Images { get; set; }

    }
}

DenimSACCOS/Areas/Admin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using DenimSACCOS.Areas.Admin.Models;
using Microsoft.AspNet.Identity;

namespace DenimSACCOS.Areas.Admin.Controllers
{
    public class HomeController : Controller
    {
        // GET: Admin/Home
        public ActionResult Index()
        {          

            if(User.Identity.IsAuthenticated)
            {
                ViewBag.AdminEmail = User.Identity.Name;
                //ViewBag.IsLoggedIn = User.Identity.IsAuthenticated;
                return View();
            }

            return RedirectToAction("Index", "../Home");
        }

        public ActionResult Mail()
        {
            return View();
        }

        public ActionResult Map()
        {
            return View();
        }
        public ActionResult Calculator()
        {
            return View();
        }
        static string tablehtml = "";

        [WebMethod]
        public string SendAmmortization(string table)
        {
            ViewBag.AmmorTable = table;
            tablehtml = table;
            return table;
        }

        [WebMethod]
        public ActionResult viewTable()
        {
            ViewBag.AmmorTable = tablehtml;
            return View();
        }


public ActionResult ContactUs(Email objModelMail, HttpPostedFileBase fileUploader)
    {
        if (ModelState.IsValid)
        {
            string from = "Email"; //example:- sourabh9303@gmail.com
            using (MailMessage mail = new MailMessage(from, objModelMail.To))
            {
                mail.Subject = objModelMail.Subject;
                mail.Body = objModelMail.Body;
                if (fileUploader != null)
                {
                    string fileName = Path.GetFileName(fileUploader.FileName);
                    mail.Attachments.Add(new Attachment(fileUploader.InputStream, fileName));
                }
                mail.IsBodyHtml = false;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.EnableSsl = true;
                NetworkCredential networkCredential = new NetworkCredential(from, "password");
                smtp.UseDefaultCredentials = true;
                smtp.Credentials = networkCredential;
                smtp.Port = 587;
                smtp.Send(mail);
                ViewBag.Message = "Sent";
                return View("ContactUs", objModelMail);
            }
        }
        else
        {
            return View();
        }
    }
        List<DenimSACCOS.Models.Gallery> files;
        public ActionResult Gallery()
        {
            files = GalleyList();
            //objHomeGallery.ImageList = files;
            //objHomeGallery = files;
            return View("Gallery", files);
        }
        public List<DenimSACCOS.Models.Gallery> GalleyList()
        {
            string folderPath = Server.MapPath("~/Areas/Gallary/");
            string[] filePaths = Directory.GetFiles(folderPath);
            files = new List<DenimSACCOS.Models.Gallery>();
            foreach (string filePath in filePaths)
            {
                string fileName = Path.GetFileName(filePath);
                files.Add(new DenimSACCOS.Models.Gallery
                {
                    ImageName = fileName.Split('.')[0].ToString(),
                    ImagePath = "~/Areas/Gallary/" + fileName
                });
            }
            List<DenimSACCOS.Models.Gallery> objimg = files.ToList();
            return objimg;
        }

    }

}

DenimSACCOS/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DenimSACCOS.Models;

namespace DenimSACCOS.Controllers
{
    public class GalleryController : Controller
    {
        // GET: Gallery
        public ActionResult Index()
        {
            files = imageslist();
            //objHomeGallery.ImageList = files;
            //objHomeGallery = files;
            return View("../Areas/Gallery",files);
        }
        List<DenimSACCOS.Models.Gallery> files;
        

        public List<DenimSACCOS.Models.Gallery> imageslist()
        {
            string folderPath = Server.MapPath("~/Areas/Gallary/");
            string[] filePaths = Directory.GetFiles(folderPath);
            files = new List<DenimSACCOS.Models.Gallery>();
            foreach (string filePath in filePaths)
            {
                string fileName = Path.GetFileName(filePath);
                files.Add(new DenimSACCOS.Models.Gallery
                {
                    ImageName = fileName.Split('.')[0].ToString(),
                    ImagePath = "~/Areas/Gallary/" + fileName
                });
            }
            List<DenimSACCOS.Models.Gallery> objimg = files.ToList();
            return objimg;
        }


    }
}

DenimSACCOS/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Services;
using DenimSACCOS.Models;
    
    
    namespace DenimSACCOS.Controllers
{
    public class HomeController : Controller
    {
      
         
       // HomeGallery objHomeGallery = null;
        public ActionResult Index()
        {
          files = imageslist();
           
            return View("Index",files);


        }
        List<DenimSACCOS.Models.Gallery> files;
        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Services()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Notice()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Saving()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Loan()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        public ActionResult Remittance()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Gallery()
        {
            files = GalleyList();
            //objHomeGallery.ImageList = files;
            //objHomeGallery = files;
            return View("Gallery", files);
        }
        public ActionResult Login()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }


        public ActionResult Downloads()
        {
            var dir = new System.IO.DirectoryInfo(Server.MapPath("~/Areas/Files/"));
            System.IO.FileInfo[] fileNames = dir.GetFiles("*.*");
            List<string> items = new List<string>();
            foreach (var file in fileNames)
            {
                items.Add(file.Name);
            }
            return View(items);
        }
        public FileResult Download(string ImageName)
        {
            var FileVirtualPath = "~/Areas/Files/" + ImageName;
            return File(FileVirtualPath, "application/force-download", Path.GetFileName(FileVirtualPath));
        }



        static string tablehtml = "";
  [WebMethod]
        public string SendAmmortization(string table)
        {
            ViewBag.AmmorTable = table;
            tablehtml = table;
            return table;
        }

        public ActionResult viewTable()
        {
            ViewBag.AmmorTable = tablehtml;
            return View();
        }

        [WebMethod]
        public ActionResult RedirectToTable()
        {
            ViewBag.AmmorTable = tablehtml;
           return redirectToView();
        }

        public ActionResult redirectToView()
        {
            return Redirect(Url.Action("viewTable", "Home"));
        }

        public List<DenimSACCOS.Models.Gallery> imageslist()
        {
            string folderPath = Server.MapPath("~/Areas/Images/");
            string[] filePaths = Directory.GetFiles(folderPath);
            files = new List<DenimSACCOS.Models.Gallery>();
            foreach (string filePath in filePaths)
            {
                string fileName = Path.GetFileName(filePath);
                files.Add(new DenimSACCOS.Models.Gallery
                {
                    ImageName = fileName.Split('.')[0].ToString(),
                    ImagePath = "../Areas/Images/" + fileName
                });
            }
            List<DenimSACCOS.Models.Gallery> objimg = files.ToList();
            return objimg;
        }
        public List<DenimSACCOS.Models.Gallery> GalleyList()
        {
            string folderPath = Server.MapPath("~/Areas/Gallary/");
            string[] filePaths = Directory.GetFiles(folderPath);
            files = new List<DenimSACCOS.Models.Gallery>();
            foreach (string filePath in filePaths)
            {
                string fileName = Path.GetFileName(filePath);
                files.Add(new DenimSACCOS.Models.Gallery
                {
                    ImageName = fileName.Split('.')[0].ToString(),
                    ImagePath = "../Areas/Gallary/" + fileName
                });
            }
            List<DenimSACCOS.Models.Gallery> objimg = files.ToList();
            return objimg;
        }

    }
}

DenimSACCOS/Controllers/MailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using DenimSACCOS.Models;

namespace DenimSACCOS.Controllers
{
    public class MailController : Controller
    {
        // GET: Mail
        public ActionResult Index(Mail _objModelMail)
        {
            ViewBag.IsEmailSent = false;
            if (ModelState.IsValid)
            {
                MailMessage mail = new MailMessage();

                mail.To.Add("krennovatest@gmail.com");
                mail.From = new MailAddress(_objModelMail.Email);

                mail.Subject = "";
                mail.Body = "Hello <b>Admin</b>,<br/><br/>New Message for you.<br/><br/><b>" + mail.Subject + ".</b><br/><br/>" + "From:&nbsp;" + _objModelMail.Name + ".<br/>Email:&nbsp; " + _objModelMail.Email + ".<br/>Contact #:&nbsp; " + _objModelMail.Mobile + ".<br/><br/>" + _objModelMail.Body + "<br/><br/>Thanks.<br/>";

                mail.IsBodyHtml = true;
                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.UseDefaultCredentials = false;
                smtp.Credentials = new System.Net.NetworkCredential("krennovatest@gmail.com", "test@123#");
                smtp.EnableSsl = true;
                smtp.Send(mail);
                ModelState.Clear();
                ViewBag.IsEmailSent = true;
                return View("../Home/Contact");

            }
            else
            {
                ViewBag.IsEmailSent = false;
                return View("../Home/Contact");
            }

        }
    }
}

DenimSACCOS/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<p><h1>About Us</h1></p>
<div class="col-sm-3">
   
    <a href="@Url.Action("Index", "Home")">
        <img src="@Url.Content("~/Images/logo in PNG.png")" height="70" width="140" />
    </a>
    <p><strong>Mission</strong></p>
    <p>usiness Affairs develops and maintains the university’s sound financial and internal control structure in alignment with OSU’s strategic plan, OUS policy and GAAP.  We emphasize a service-oriented, team approach to providing financial information, systems, and policies that meet fiduciary and regulatory responsibilities, address the operational needs of the University’s departments, and serve the needs of our students, parents, alumni, fellow employees, and sponsor </p>
</div>
<div class="col-sm-3">
    <a href="@Url.Action("Index", "Home")">
        <img src="@Url.Content("~/Images/logo in PNG.png")" height="70" width="140" />
    </a>
    <p><strong>Vision</strong></p>
    <p>To distinguish Prudential as an admired multinational financial services leader, trusted partner, and provider of innovative solutions for growing and protecting wealth. </p>
</div>
<div class="col-sm-3">
    <a href="@Url.Action("Index", "Home")">
        <img src="@Url.Content("~/Images/logo in PNG.png")" height="70" width="140" />
    </a>
    <p><strong>principle</strong></p>
    <p>Integrity
Professionalism
Exceptional customer service
Fiscal conservatism and compliance
Collaborative and transparent
Continuous improvement
Respectful diversity </p>
</div>
<div class="col-sm-3">
    <a href="@Url.Action("Index", "Home")">
        <img src="@Url.Content("~/Images/logo in PNG.png")" height="70" width="140" />
    </a>
    <p><strong>BOD And Management Structure</strong></p>
    <p>usiness Affairs develops and maintains the university’s sound financial and internal control structure in alignment with OSU’s strategic plan, OUS policy and GAAP.  We emphasize a service-oriented, team approach to providing financial information, systems, and policies that meet fiduciary and regulatory responsibilities, address the operational needs of the University’s departments, and serve the needs of our students, parents, alumni, fellow employees, and sponsor </p>
</div>

DenimSACCOS/Views/Home/Contact.cshtml
@model DenimSACCOS.Models.Mail
@{
    ViewBag.Title = "Contact";
  
}
<h2>@ViewBag.Title</h2>
<style>
    #map {
        
        height: 300px;
        width: 100%;
        
                
    }
</style>
 
    <div id="map"></div>
    <script>
	//https://www.w3schools.com/html/tryit.asp?filename=tryhtml5_geolocation
      function initMap() {
       // var uluru = {lat: -25.363, lng: 131.044};
	    var uluru = {lat: 27.7041208, lng: 85.34664029999999};
        var map = new google.maps.Map(document.getElementById('map'), {
          zoom: 16,
          center: uluru
        });
        var marker = new google.maps.Marker({
          position: uluru,
          map: map
        });
      }
    </script>
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBy4hpAV8o3AiIUlFiOAEwNDwehH8JjCFw&callback=initMap">
    </script>

<div class="col-sm-1">
</div>
    <div class="col-sm-5">
        <div class="col">
            <address>
                <br />
               <h3> Boudha, Nepal 98052-6399</h3>
             <h4>P:  980-3608342</h4>
                
</address>
  <address>
                <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
                <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
            </address>
        </div>
    </div>

    <div class="col-sm-6">

        <div id="contact-form">
            <h4>Write to us</h4>
@using (Html.BeginForm("Index", "Mail"))
{

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.TextBoxFor(model => model.Name, null, new { id = "name", placeholder = "Enter Name", @class = "form-control" })<br />
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
        <div class="form-group">
            @Html.TextBoxFor(model => model.Email, null, new { id = "email", placeholder = "Enter Email", @class = "form-control" })<br />
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
            <div class="form-group">
                @Html.TextBoxFor(model => model.Mobile, null, new { id = "mobile", placeholder = "Enter Mobile", @class = "form-control" })<br />
                @Html.ValidationMessageFor(model => model.Mobile, "", new { @class = "text-danger" })
                </div>

        
                <div class="form-group">
                    @Html.TextBoxFor(model => model.Body, null, new { id = "message", placeholder = "Enter Message", @class = "form-control" })<br />
                    @Html.ValidationMessageFor(model => model.Body, "", new { @class = "text-danger" })
                    </div>
                    <button type="submit" class="btn btn-success">Send</button>

                    }
                </div>
    </div>

DenimSACCOS/Views/Home/Downloads.cshtml
@{
    ViewBag.Title = "Downloads";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}



@model List<string>

<div style="margin-left:10%">
    <h1>Downloads</h1>
    <table width="400" height="250" style="font:bold 15px large,verdana">
        <tr>
            <th><h3><u><strong>Documents</strong></u></h3></th>
            <th><h3><u><strong>Links</strong></u></h3></th>
        </tr>
        @for (var i = 0; i <= Model.Count - 1; i++)
        {
            <tr>
                <td><strong>@Model[i].ToString()</strong></td>
                <td>@Html.ActionLink("Download", "Download", new { ImageName = @Model[i].ToString() }) </td>
            </tr>
        }
    </table>
</div> 

DenimSACCOS/Views/Home/Gallery.cshtml
@model IEnumerable<DenimSACCOS.Models.Gallery>
@{
    ViewBag.Title = "Gallery";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}
<h2>Gallery</h2>
<div class="container">
  

    <div class="row gallery">
       
        @foreach (var item in Model)
            {
               
            <div class="col-sm-3 wowload fadeInUp"><a href="@Html.DisplayFor(modelItem => item.ImagePath)" class="gallery-image" data-gallery>
                <img src='~/@Html.DisplayFor(modelItem => item.ImagePath)' class="img-responsive"></a></div>
        }
    </div>

</div>

DenimSACCOS/Views/Home/Loan.cshtml
@{
    ViewBag.Title = "Loan";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}

<div class="col-lg-1"></div>
    <div class="col-lg-11">
        <h2>Loan</h2>

        <strong>Loans and Advance</strong>
        <br>
        Medi/um and Long-Term (Industrial, Trading etc.)
        Hire Purchase
        Housing Loan
        Loan against Securities & Fixed Deposit
        Real Estate Loan
        Deprived Sector Loan
        Education Loan

        Reliable Flexi/Personal Loan

        Gold Loan
        OverDraft Loan
        <br>
    </div>

DenimSACCOS/Views/Home/Login.cshtml
@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}

<h2>Login</h2>

<div class="container content">
    <div class="row">
        <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3">
            <form class="reg-page">
                <div class="reg-header">
                    <h2>Login to your account</h2>
                </div>

                <div class="input-group margin-bottom-20">
                    <span class="input-group-addon"><i class="fa fa-user"></i></span>
                    <input type="text" placeholder="Username" class="form-control">
                </div>
                <div class="input-group margin-bottom-20">
                    <span class="input-group-addon"><i class="fa fa-lock"></i></span>
                    <input type="password" placeholder="Password" class="form-control">
                </div>

                <div class="row">
                    <div class="col-md-6 checkbox">
                        <label><input type="checkbox"> Stay signed in</label>
                    </div>
                    <div class="col-md-6">
                        <button class="btn-u pull-right" type="submit">Login</button>
                    </div>
                </div>

                <hr>

                <h4>Forget your Password ?</h4>
                <p>no worries, <a class="color-green" href="#">click here</a> to reset your password.</p>
            </form>
        </div>
    </div><!--/row-->
</div>

DenimSACCOS/Views/Home/Notice.cshtml
@{
    ViewBag.Title = "Notice";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}

<h2>Notice</h2>

DenimSACCOS/Views/Home/Remittance.cshtml
@{
    ViewBag.Title = "Remittance";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}
<div class="col-md-1">
</div>
<div class="col-md-11">
    <h2>Remittance Services</h2>
    <strong>Remittance Schemes</strong>
<br>
    Remittance Services via our own inhouse Remittance software (Reliable Remit). Money can be sent and paid from more than 2600 payout agents (for more detail visit our website: www.reliableremit.com).
</div>

DenimSACCOS/Views/Home/Saving.cshtml
@{
    ViewBag.Title = "Saving";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}
<div class="col-lg-1"></div>
    <div class="col-lg-11">
        <h2>Saving</h2>

        <strong>Deposit & Saving Schemes</strong>
        <br>
        Time Deposit Account ranging from 3 Months and above
        Normal Saving, Corporate Saving, Special Saving Deposit
        Fixed Deposit
        <br>
    </div>

DenimSACCOS/Views/Home/Services.cshtml
@{
    ViewBag.Title = "Services";
    Layout = "~/Views/Shared/_FinanceLayout.cshtml";
}

<h2>Services</h2>

DenimSACCOS/Views/Home/viewTable.cshtml
@{
    ViewBag.Title = "Index";

}

<center><h2>Ammortization Table</h2></center>

<div class="box-body table-responsive " id='datatable'>
    <center>
        @Html.Raw(@ViewBag.AmmorTable)
    </center>
</div>